# -*- coding: utf-8 -*-

import re


TLDR_PATTERNS = [
    u'tl;dr',
    u'tl:dr',
    u'tl:dr:',
    u'(tl:dr)',
    u'tl:dr-',
    u'tl;dr -',
    u'**tldr;',
    u'tl/dr:',
    u'tldr;',
    u'tl;dr:',
    u'tldr :',
    u'tldr:',
    u'**tl;dr:**',
    u'**tl;dr**',
    u'tl,dr',
    u'**tl;dr** -',
    u'**tl;dr',
    u'**tl;dr:',
    u'tldr -',
    u'tl;dr-',
    u'*tl;dr*',
    u'tl;dr/tifu',
    u'tl;dr :',
    u'tl;dr: \n',
    u'**tl;dr** –',
    u'tl/dr',
    u'tldr:\n',
    u'tl;dr.',
    u'**tl;dr** \n\n',
    u'tl;dr tl;dr:',
    u'tl;dr`',
    u'**tl;dr -',
    u'tldr\n',
    u'tldr',
    u'tl;dr  --',
    u'tl;dr\n',
    u'**tl;dr** :',
    u'tl:dr\n',
    u'tl;dr,',
    u'tdrl;',
    u'tdlr:',
    u'tl-dr - ',
    u'tl.dr:',
    u'tl: idr:',
]

TIFU_PATTERNS = [
    re.compile(r"today i fucked up by (.*)"),
    re.compile(r"nsfw tifu by (.*)"),
    re.compile(r"tifupdate \- tifu by (.*)"),
    re.compile(r"tifuupdate\: tifu at work \- (.*)"),
    re.compile(r"reddit\: tifu by (.*)"),
    re.compile(r"tifupdate\: tifu by (.*)"),
    re.compile(r"update\: tifu by (.*)"),
    re.compile(r"sya\-ifu (.*)"),
    re.compile(r"tifu by (.*)"),
    re.compile(r"\[.*\] tifu by (.*)"),
    re.compile(r"\[.*\] (.*)"),
    re.compile(r"\(.*\)tifu (.*)"),
    re.compile(r"\(.*\) tifu (.*)"),
    re.compile(r"yifu by (.*)"),
    re.compile(r"tdif by (.*)"),
    re.compile(r"by (.*)"),
    re.compile(r"tifupdate: (.*)"),
    re.compile(r"tifupdate (.*)"),
    re.compile(r"tifu-by (.*)"),
    re.compile(r"tifu:by (.*)"),
    re.compile(r"\#tifu (.*)"),
    re.compile(r"tifu while  (.*)"),
    re.compile(r"tifu and (.*)"),
    re.compile(r"tifu when (.*)"),
    re.compile(r"tifu \(.*\) by (.*)"),
    re.compile(r"tifu\(.*\) by (.*)"),
    re.compile(r"tifu\(.*\) (.*)"),
    re.compile(r"tifu\, (.*)"),
    re.compile(r"tifu\: (.*)"),
    re.compile(r"tifu\- (.*)"),
    re.compile(r"tifu; (.*)"),
    re.compile(r"tifu\. (.*)"),
    re.compile(r"tifu \- (.*)"),
    re.compile(r"tifu (.*)"),
    re.compile(r"tip\/tifu (.*)"),
    re.compile(r"tip\: (.*)"),
    re.compile(r"tip by (.*)"),
    re.compile(r"tip (.*)"),
]
